### ISSUE TITLE
Implement Telluric downloads

### ISSUE THREAD

**Issue by brunosan** [satellogic/open-impact#3]
Switch over to download the data using Telluric, not the web explorer version.

**Comment by astrojuanlu** [comment]
Let's look into this next week!

**Comment by brunosan** [comment]
Happening on `telluric` branch. Currently able to authenticate, search and retrieve scene_ids

**Comment by aguspo** [comment]
Hi! It's Agus here!

**Comment by brunosan** [comment]
To validate downloads we could try reading them, check these options out:
* https://gis.stackexchange.com/questions/258915/tiff-and-tfw-file-validation
* https://docs.python.org/3/library/imghdr.html
* http://effbot.org/imagingbook/image.htm#tag-Image.Image.verify
