### ISSUE TITLE
conda environment is not shareable

### ISSUE THREAD

**Issue by astrojuanlu** [satellogic/open-impact#4]
I had to make these changes to `environment.yml` to make it work on Linux:

```diff
diff --git a/environment.yml b/environment.yml
index 454b974..dd853dd 100644
--- a/environment.yml
+++ b/environment.yml
@@ -4,7 +4,6 @@ channels:
 - defaults
 dependencies:
 - affine=2.2.0=py_0
-- appnope=0.1.0=py36_0
 - asn1crypto=0.24.0=py36_0
 - attrs=17.4.0=py_0
 - backports=1.0=py36_1
@@ -120,7 +119,7 @@ dependencies:
 - pytz=2018.3=py_0
 - pywavelets=0.5.2=py36_1
 - pyzmq=17.0.0=py36_3
-- qt=5.6.2=h9e3eb04_4
+- qt=5.6.2
 - qtconsole=4.3.1=py36_0
 - rasterio=0.36.0=py36_3
 - readline=7.0=0
@@ -151,12 +150,9 @@ dependencies:
 - xz=5.2.3=0
 - zeromq=4.2.3=2
 - zlib=1.2.11=0
-- anaconda=custom=py36ha4fed55_0
 - intel-openmp=2018.0.0=8
-- libgfortran=3.0.1=h93005f0_2
-- mkl=2018.0.2=1
-- numpy=1.14.2=py36ha9ae307_0
-- scipy=1.0.0=py36h1de22e9_0
+- numpy=1.14.2
+- scipy=1.0.0
 - pip:
   - backports.functools-lru-cache==1.5
   - dask==0.17.2
```

The reason is that, since the introduction of newer conda versions, `environment.yml` files are no longer cross platform by default:

https://github.com/conda/conda/issues/6220

(Other related issues: https://github.com/conda/conda/issues/1033 https://github.com/ContinuumIO/anaconda-issues/issues/546)

The solution is to export the environment with the `--no-builds` flag, which needs conda >= 4.3.31 to work. _However_, be careful with which conda version you use because now conda-forge is in an "everything is broken" state which hopefully will go away soon, but not before AnacondaCON https://github.com/conda-forge/conda-feedstock/issues/43

So my advice is to use this in the meanwhile:

```
$ conda install "conda<4.4" -c conda-forge
```

As a last note, there's an open issue about pip packages in `environment.yml` files https://github.com/conda/conda/issues/5901 that might end up in broken installations, so my advice is to remove them from the `environment.yml` file and tell the users to install them manually after creating the environment.

Nobody said it would be easy :)

**Comment by brunosan** [comment]
oh boy... Thanks @Juanlu001 

The best solution, for now, is probably to add documentation on the different `environment.yml` for Mac and Linux [imo most cases], and point people here for more info.

Could you please send the file as a PR?

**Comment by astrojuanlu** [comment]
Sure!
