### ISSUE TITLE
Stanford hyperspectral image cannot be downloaded

### ISSUE THREAD

**Issue by aliciavalero** [satellogic/open-impact#9]
The Stanford hyperspectral notebook cannot be run because the user lacks the necessary permissions to download the image.

**Comment by brunosan** [comment]
Thanks @aliciavalero. It didn´t pass internal QA, so it´s not on the catalog. We are giving it another shot this week.

**Comment by brunosan** [comment]
Closing here. Several hyperspectral images are functionally equivalent (same sensor, water+builtup+nature, ...). E.g. https://telluric.satellogic.com/explorer/shared/941058ca-cf8b-4abe-bd29-cad944a924df/Open_Impact_Hyperspectral-RGB_Enhanced-from_2017-09-28_111233-to_2018-04-22_152035
